# Generated by Django 3.0.8 on 2020-07-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telefonera_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telefono',
            options={'ordering': ['pk']},
        ),
    ]
