# Generated by Django 3.0.8 on 2020-07-11 17:03

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telefonera_app', '0002_auto_20200710_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='foto',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='formato de imagen .jpeg or .png tamańo máximo: 10 MB dimensiones recomendadas: 1372 x 772 px', null=True, upload_to='images/foto', verbose_name='Foto'),
        ),
    ]
