# Generated by Django 3.0.8 on 2020-07-12 01:31

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('poster', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Insertar poster en formato .jpeg or .png | Tamaño máximo: 10 MB | Dimensiones recomendadas: 1372 x 772 px', null=True, upload_to='images/poster', verbose_name='Poster')),
                ('año', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_app.Year')),
            ],
        ),
    ]
