# Generated by Django 3.0.8 on 2020-07-11 17:29

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_auto_20200711_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Insertar poster en formato .jpeg or .png Tamaño máximo: 10 MB Dimensiones recomendadas: 1372 x 772 px', null=True, upload_to='images/poster', verbose_name='Poster'),
        ),
    ]
